name: SSH Test

on: [push]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Remote Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_SSH_USER }}
          key: ${{ secrets.DOCKER_SSH_KEY }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            echo "✅ Successfully connected to the server!"
            uname -a
